### ISSUE TITLE
Replace the MODIS Rapid Response handler with Worldview/GIBS

### ISSUE THREAD

**Issue by raymondben** [AustralianAntarcticDivision/bowerbird#1]
See https://earthdata.nasa.gov/earth-observation-data/near-real-time/rapid-response and earthdata.nasa.gov/about/science-system-description/eosdis-components/global-imagery-browse-services-gibs

**Comment by mdsumner** [comment]
I have updated readrapid_response  in raadtools, there it should use a *files function in raadfiles but I've just temporarily hacked it in place until we move to GIBS. (There's something wrong with these old files anyway, some are zero-size).

**Comment by raymondben** [comment]
Moved to https://github.com/AustralianAntarcticDivision/blueant/issues/6
