### ISSUE TITLE
Mike's postrev notes

### ISSUE THREAD

**Issue by mdsumner** [AustralianAntarcticDivision/bowerbird#14]
Just a few notes, mostly minor. 

vignette("bowerbird") is mostly present in the readme, should the readme be reduced? (How are they kept in-sync?)

"Sea Ice Trends and Climatologies from SMMR and SSM/I-SSMIS, Version 2" is not in the help for `bb_example_sources`, but Nimbus is (and is not in the example object)

## seealso
- put `bb_sync`, `bb_source`, and `bb_config` in each other's see also

## spelling consistency
- synchronize/synchronisation (-ize is consistent elsewhere)
- typo in `bb_source` "providedso"

## value
- `bb_source` value is "tibble", consider "data frame" and state that it will have columns as per this function's arguments (excluding warn_empty_auth)
- `bb_data_sources`, `bb_example_sources` - value is "tibble", maybe link to bb_source value
- other functions also only list "tibble"

## examples

Consider a dontrun for `bb_sync`, I think it's a nice place to repeat the overall pattern with an example that can be copy/pasted in whole: 

```R
td <- tempdir()  ## strictly, user should specify this explicitly for control over file system
cf <- bb_config(local_file_root = td)

## Bowerbird must then be told which data sources to synchronize. 
## Let’s use data from the Australian 2016 federal election, which is provided as one 
## of the example data sources:
my_source <- subset(bb_example_sources(),id=="aus-election-house-2016")

## add this data source to the configuration
cf <- bb_add(cf,my_source)
## Once the configuration has been defined and the data source added to it, run the sync process:
status <- bb_sync(cf)

## see the fruits of our labour (files are CSVs in this data source)
head(list.files(td, recursive = TRUE, pattern = "csv$"))

## we can run this at any later time and our repository will update if the source has changed
status2 <- bb_sync(cf)

```

**Comment by raymondben** [comment]
Thanks. All addressed now.
