### ISSUE TITLE
R depends version 

### ISSUE THREAD

**Issue by mdsumner** [AustralianAntarcticDivision/bowerbird#9]
Suggest to add a minimal R version,  say 3.3.1 -  Sara just tried installing on 3.0.0 and this version check would help guide a new starter

**Comment by raymondben** [comment]
What was the issue with 3.0.0? I'm happy to add a minimal R version but seems worth knowing what the problem was, maybe it can be avoided. Some users might run older versions of R deliberately and not be keen to upgrade ...

**Comment by mdsumner** [comment]
Yeah - and fair enough, :)  this is hard because I can't access a Mac but here's what she saw on R 3.0.0, implies that sys-binary is not built that far back (it was released on January 2017, but doesn't itself have a Depends). 
Mac OS X Yosemite 10.10.3

>install_github("AustralianAntarcticDivision/bowerbird",build_vignettes=TRUE)
> Downloading github repo AustralianAntarcticDivision/bowerbird@master
> Installing bowerbird
> Installing dependencies for bowerbird:
> assertthat, dplyr, openssl, R.utils, rmarkdown, sys, archive, knitr, testthat, covr, knitr
>   package ‘sys’ is available as a source package but not as a binary

Also, on 3.3.0 was seen this which might pin the requirement a bit: 

```
Error : object ‘evaluate’ is not exported by 'namespace:glue'
ERROR: lazy loading failed for package ‘archive’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/archive’
Installation failed: Command failed (1)
```

It's hard to check on older versions, I definitely err on the side of "too up to date" but it can be tricky to verify back enough.  It looks like it's a goer on 3.3.0 at least

I don't have a strong opinion, just wanted to record this

**Comment by raymondben** [comment]
OK, done (3.3.0). Now that you point it out, I'm not surprised that `archive` and `sys` are problematic for anything other than recent R versions. Ta.
